<a href="https://colab.research.google.com/github/pjsun2/2023-codespace/blob/main/%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D/230914_2%ED%9A%8C%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import numpy as np

In [24]:
x = list(range(10))
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
x * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
x + x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
x2 = [n*2 for n in x]
x2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [28]:
xa = np.array(range(10))
xa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
print(type(x))
print(type(xa))

<class 'list'>
<class 'numpy.ndarray'>


In [30]:
len(xa)

10

In [31]:
x3 = ['a',1,2,5]
x3

['a', 1, 2, 5]

In [32]:
xa1 = np.array(x3)
xa1

array(['a', '1', '2', '5'], dtype='<U21')

In [33]:
xa * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
xa - xa

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
list(map(lambda n: n*2, x))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [37]:
xa2 = np.array(range(-5,5))
xa2

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [38]:
np.abs(xa2) #abs : 절대값

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4])

In [40]:
print('이거')

이거


In [41]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
